#!/bin/bash

# Print the introduction text
echo -e "##########################################\n"
echo "Welcome to Will Pringle's A4 Testing Suite"
echo -e "\n##########################################\n"

